name: task_manager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^11.0.0
  firebase_core: ^2.25.4
  cloud_functions: ^4.6.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5

  google_sign_in: ^5.4.0
  local_auth: ^2.1.0
  intl: ^0.17.0
  provider: ^6.0.0
  flutter_local_notifications: ^9.1.5
  shared_preferences: ^2.0.15
  fl_chart: ^0.62.0
  image_picker: ^0.8.5+3
  table_calendar: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Butler
      fonts:
        - asset: assets/fonts/Butler_ExtraBold.otf
    - family: SFProM
      fonts:
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.otf
    - family: SFProMed
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.otf

