// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_GUSDKcSGf5NtzHxZIX30uhfHNZs_2QM',
    appId: '1:679878979200:web:6ed1a47012621d473d0065',
    messagingSenderId: '679878979200',
    projectId: 'task-manager-wuproject01',
    authDomain: 'task-manager-wuproject01.firebaseapp.com',
    storageBucket: 'task-manager-wuproject01.appspot.com',
    measurementId: 'G-TZQBSN6JZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiPgSBqEebFYy74fcFjyXqloZDer7_zP8',
    appId: '1:679878979200:android:d21936e4f7f1902e3d0065',
    messagingSenderId: '679878979200',
    projectId: 'task-manager-wuproject01',
    storageBucket: 'task-manager-wuproject01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgGHSBkSguA6sPITVtpI8l9R1fkYpmlGI',
    appId: '1:679878979200:ios:dce69a47ff6bc2053d0065',
    messagingSenderId: '679878979200',
    projectId: 'task-manager-wuproject01',
    storageBucket: 'task-manager-wuproject01.appspot.com',
    iosClientId: '679878979200-n0khj33j9gmthjroa86qca6mtr1s735m.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

}